services:
  - type: web
    name: bot-argento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PIONEX_API_KEY
        sync: false
      - key: PIONEX_SECRET_KEY
        sync: false
